<?php

namespace ProjectUserBundle\Repository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findNewUsers(){
        return $this->findBy(array(), array('id' => 'desc'), 5);
    }
}