<?php

namespace ProjectBundle\Repository;

/**
 * GenresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenresRepository extends \Doctrine\ORM\EntityRepository
{
}
