<?php

namespace ProjectBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
	public function listAndTestLinkPlayers()
	{
		$listOfPlayers = $this->findAll();

		foreach($listOfPlayers as $player){
			var_dump($player->getlinkExample());
		}

		return $listOfPlayers;
	}
}
