<?php

namespace ProjectBundle\Repository;

/**
 * PlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLatestPlaylists(){

        return $this->findBy(array(), array('dateAdd' => 'desc'), 5);

    }
}
