<?php

namespace ProjectBundle\Repository;

/**
 * PlaylistsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaylistsRepository extends \Doctrine\ORM\EntityRepository
{
}
