<?php

namespace ProjectBundle\Repository;

/**
 * SoundsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoundsRepository extends \Doctrine\ORM\EntityRepository
{
}
