<?php

namespace ProjectBundle\Repository;

/**
 * WallpapersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WallpapersRepository extends \Doctrine\ORM\EntityRepository
{
}
